services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webapp:
    build: ./webapp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webapp:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  scraper:
    build: ./scraper
    volumes:
      - ./scraper:/app
    depends_on:
      - db
    env_file:
      - .env
